#!/usr/bin/env bash
# the ol' Fizzbuzz test

x=1
while ((x<=100))
	do

	if [ $((x%15)) == 0 ]
	then
		echo "FizzBuzz"

	elif [ $((x%3)) == 0 ]
	then
		echo "Fizz"

	elif [ $((x%5)) == 0 ]
	then
		echo "Buzz"

	else
		echo "$x"
	fi

	((x=x+1))
done
