#!/usr/bin/env bash
# this script prints "Best School" 10 times, except for "hi" on the 9th line

x="1"

while [ $x -le 10 ]

do
	echo "Best School"
	
	if 
		[ $x -eq 9 ]
	then
		echo "Hi"
	fi
		x=$(( x + 1 ))	
done
