#!/usr/bin/env bash
#"bad luck from" on 4, 9, & 17 while counting to 20

x="1"
while [ $x -le 20 ]

	do 
		echo "$x"

	case $x in
	4) 
		echo "bad luck from China";;
	9) 
		echo "bad luck from Japan";;
	17)  
		echo "bad luck from Italy";;
	esac
	
	x=$(( x + 1 ))

done
